import type { Work, WorkCategory } from '@/types'

// Generado a partir de public/img/trabajos: cada foto existe en -sm (640px) y -lg (1600px).
export const workCategories: { id: WorkCategory | 'todos'; label: string }[] = [
  { id: 'todos', label: 'Todos' },
  { id: 'vehicular', label: 'Branding vehicular' },
  { id: 'solar', label: 'Control solar' },
  { id: 'stickers', label: 'Stickers premium' },
  { id: 'espacios', label: 'Espacios y señalética' },
  { id: 'letreros', label: 'Letreros y POP' },
  { id: 'textil', label: 'Textiles' },
]

export const works: Work[] = [
  {
    slug: 'vehicular-dulce-antojo',
    category: 'vehicular',
    title: 'Branding de furgoneta · Dulce Antojo',
    ratio: 0.75,
    color: '#555651',
  },
  {
    slug: 'vehicular-dulce-antojo-lateral',
    category: 'vehicular',
    title: 'Furgoneta Dulce Antojo, vista lateral',
    ratio: 0.562,
    color: '#6f7174',
  },
  {
    slug: 'vehicular-yumm',
    category: 'vehicular',
    title: 'Branding posterior · Dulce Antojo y Yumm',
    ratio: 0.562,
    color: '#84878f',
  },
  {
    slug: 'vehicular-cargolan',
    category: 'vehicular',
    title: 'Camión de flota · Cargolan',
    ratio: 0.75,
    color: '#6e737e',
  },
  {
    slug: 'vehicular-instalacion-camion',
    category: 'vehicular',
    title: 'Instalación de vinil en camión',
    ratio: 0.75,
    color: '#675d65',
  },
  {
    slug: 'vehicular-migaan',
    category: 'vehicular',
    title: 'Camioneta corporativa · Migaan AMG',
    ratio: 1.778,
    color: '#777676',
  },
  {
    slug: 'vehicular-upper',
    category: 'vehicular',
    title: 'Furgoneta de flota · Upper',
    ratio: 1.778,
    color: '#5c616a',
  },
  {
    slug: 'vehicular-upper-frente',
    category: 'vehicular',
    title: 'Furgoneta Upper, vista frontal',
    ratio: 0.562,
    color: '#52677f',
  },
  {
    slug: 'vehicular-1700-custodia',
    category: 'vehicular',
    title: 'Camioneta · 1700 Custodia',
    ratio: 0.562,
    color: '#6f6e6d',
  },
  {
    slug: 'vehicular-instalador',
    category: 'vehicular',
    title: 'Instalación profesional',
    ratio: 0.753,
    color: '#6f6867',
  },
  {
    slug: 'vehicular-motorhome',
    category: 'vehicular',
    title: 'Motorhome personalizado',
    ratio: 0.753,
    color: '#666666',
  },
  {
    slug: 'vehicular-motorhome-frente',
    category: 'vehicular',
    title: 'Motorhome, vista frontal',
    ratio: 0.753,
    color: '#727478',
  },
  {
    slug: 'vehicular-van-rosa',
    category: 'vehicular',
    title: 'Van rosa · Dulce Secreto',
    ratio: 0.753,
    color: '#73525a',
  },
  {
    slug: 'vehicular-van-rosa-lateral',
    category: 'vehicular',
    title: 'Van Dulce Secreto, vista lateral',
    ratio: 1.328,
    color: '#6e5f63',
  },
  {
    slug: 'solar-instalacion',
    category: 'solar',
    title: 'Instalación de película de control solar',
    ratio: 0.753,
    color: '#746d60',
  },
  {
    slug: 'solar-casa-jardin',
    category: 'solar',
    title: 'Película de control solar residencial',
    ratio: 0.753,
    color: '#797d7b',
  },
  {
    slug: 'solar-ventanal',
    category: 'solar',
    title: 'Ventanal con control solar',
    ratio: 0.753,
    color: '#848381',
  },
  {
    slug: 'solar-residencia',
    category: 'solar',
    title: 'Residencia con película antisolar',
    ratio: 0.753,
    color: '#656457',
  },
  {
    slug: 'solar-local-vidrio',
    category: 'solar',
    title: 'Local comercial con vidrio protegido',
    ratio: 0.753,
    color: '#8e8d89',
  },
  {
    slug: 'solar-fachada-comercial',
    category: 'solar',
    title: 'Fachada de vidrio comercial',
    ratio: 0.753,
    color: '#64625c',
  },
  {
    slug: 'solar-oficina',
    category: 'solar',
    title: 'Oficina con película de control solar',
    ratio: 0.753,
    color: '#7f7d7c',
  },
  {
    slug: 'solar-casa-fachada',
    category: 'solar',
    title: 'Fachada residencial',
    ratio: 0.753,
    color: '#726d69',
  },
  {
    slug: 'solar-puerta-vidrio',
    category: 'solar',
    title: 'Puerta de vidrio con película',
    ratio: 0.753,
    color: '#808280',
  },
  {
    slug: 'solar-terraza',
    category: 'solar',
    title: 'Terraza con control solar',
    ratio: 0.753,
    color: '#676260',
  },
  {
    slug: 'solar-casa-dos-pisos',
    category: 'solar',
    title: 'Casa de dos pisos',
    ratio: 0.753,
    color: '#6f5d5c',
  },
  {
    slug: 'solar-casa-urbanizacion',
    category: 'solar',
    title: 'Casa en urbanización',
    ratio: 0.753,
    color: '#909192',
  },
  {
    slug: 'solar-casa-moderna',
    category: 'solar',
    title: 'Casa moderna con ventanas protegidas',
    ratio: 0.753,
    color: '#7d7e77',
  },
  {
    slug: 'stickers-coleccion',
    category: 'stickers',
    title: 'Colección de stickers temáticos',
    ratio: 0.716,
    color: '#a79d96',
  },
  {
    slug: 'stickers-tamanos',
    category: 'stickers',
    title: 'Planchas de stickers A5 y A4',
    ratio: 1.773,
    color: '#d3ccc8',
  },
  {
    slug: 'stickers-codicia',
    category: 'stickers',
    title: 'Stickers premium · Codicia',
    ratio: 0.753,
    color: '#937f7d',
  },
  {
    slug: 'stickers-indomable',
    category: 'stickers',
    title: 'Stickers en alto relieve · Indomable',
    ratio: 0.753,
    color: '#a99b91',
  },
  {
    slug: 'stickers-luvart-exhibidor',
    category: 'stickers',
    title: 'Exhibidor LuvArt',
    ratio: 0.753,
    color: '#7d7d7a',
  },
  {
    slug: 'stickers-furia',
    category: 'stickers',
    title: 'Exhibidor de stickers · Furia',
    ratio: 0.753,
    color: '#716b67',
  },
  {
    slug: 'stickers-sweet-coffee',
    category: 'stickers',
    title: 'Stickers · Sweet & Coffee',
    ratio: 0.753,
    color: '#90908a',
  },
  {
    slug: 'espacios-pared-sanitela',
    category: 'espacios',
    title: 'Brandeo de pared · Sanitela',
    ratio: 0.654,
    color: '#99958b',
  },
  {
    slug: 'espacios-vitrina-millennials',
    category: 'espacios',
    title: 'Vitrina impresa · Millennials',
    ratio: 1.027,
    color: '#70605e',
  },
  {
    slug: 'espacios-senaletica',
    category: 'espacios',
    title: 'Señalética corporativa',
    ratio: 1.0,
    color: '#5a657c',
  },
  {
    slug: 'espacios-senaletica-seguridad',
    category: 'espacios',
    title: 'Señalética de seguridad',
    ratio: 0.995,
    color: '#839a83',
  },
  {
    slug: 'espacios-arenado-oficina',
    category: 'espacios',
    title: 'Vinil arenado · 1700 Custodia',
    ratio: 0.562,
    color: '#6e6a67',
  },
  {
    slug: 'espacios-arenado-texadvisory',
    category: 'espacios',
    title: 'Vinil arenado · Texadvisory',
    ratio: 0.486,
    color: '#6f6968',
  },
  {
    slug: 'espacios-troquelado-fundacion',
    category: 'espacios',
    title: 'Vinil troquelado · Fundación Acción Solidaria',
    ratio: 0.76,
    color: '#bcbcb6',
  },
  {
    slug: 'espacios-troquelado-fedenador',
    category: 'espacios',
    title: 'Vinil troquelado · Fedenador',
    ratio: 0.959,
    color: '#979597',
  },
  {
    slug: 'espacios-troquelado-doctorplus',
    category: 'espacios',
    title: 'Vinil troquelado · DoctorPlus',
    ratio: 0.638,
    color: '#7c818d',
  },
  {
    slug: 'letreros-upper-dia',
    category: 'letreros',
    title: 'Letrero corpóreo · Upper',
    ratio: 2.192,
    color: '#607077',
  },
  {
    slug: 'letreros-upper-led',
    category: 'letreros',
    title: 'Letrero corpóreo LED · Upper',
    ratio: 2.115,
    color: '#393c33',
  },
  {
    slug: 'letreros-gigantografia-iplas',
    category: 'letreros',
    title: 'Gigantografía · Iplas',
    ratio: 2.949,
    color: '#8f879c',
  },
  {
    slug: 'pop-stand-stavian',
    category: 'letreros',
    title: 'Stand con estructura · Stavian',
    ratio: 1.26,
    color: '#787e79',
  },
  {
    slug: 'pop-backing-iplas',
    category: 'letreros',
    title: 'Backing curvo · Iplas',
    ratio: 0.975,
    color: '#5c5c66',
  },
  {
    slug: 'pop-backing-dunkin',
    category: 'letreros',
    title: "Backing · Dunkin'",
    ratio: 1.702,
    color: '#7b5566',
  },
  {
    slug: 'pop-backing-holcim',
    category: 'letreros',
    title: 'Backing fijo · Holcim',
    ratio: 1.012,
    color: '#85827d',
  },
  {
    slug: 'pop-stand-kapoor',
    category: 'letreros',
    title: 'Stands en PVC · Kapoor',
    ratio: 1.201,
    color: '#5d7494',
  },
  {
    slug: 'pop-counter-cristal-master',
    category: 'letreros',
    title: 'Counter · Cristal Master',
    ratio: 0.896,
    color: '#75757f',
  },
  {
    slug: 'textil-buzos',
    category: 'textil',
    title: 'Buzos personalizados',
    ratio: 1.7,
    color: '#5b5656',
  },
  {
    slug: 'textil-camisetas',
    category: 'textil',
    title: 'Camisetas bordadas · Upper',
    ratio: 0.723,
    color: '#56595b',
  },
  {
    slug: 'textil-bordado-upper',
    category: 'textil',
    title: 'Bordado · Upper',
    ratio: 0.81,
    color: '#595e5c',
  },
  {
    slug: 'textil-roomye',
    category: 'textil',
    title: 'Camisetas DTF · Roomye',
    ratio: 0.747,
    color: '#aeaead',
  },
]

export const workImage = (slug: string, size: 'sm' | 'lg' = 'sm') =>
  `/img/trabajos/${slug}-${size}.webp`
